name: shelf_gcp_utils
description: Dart utilities for working with GCP products in shelf servers.
version: 0.0.0-a1
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.1
  json_utils:
    git: https://github.com/enspyrco/json_utils

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
